### PR TITLE
Upgrade packages, tests and documentation

### PR DESCRIPTION
**Pull request by egyptianbman**

### CODE REVIEW

**Review by stephenfairchild — APPROVED** [review]
LGTM!

**Comment by headyj** [comment]
@egyptianbman @stephenfairchild I guess it will not work with neo4j 4 right? Did you test it?

**Comment by egyptianbman** [comment]
I ran the tests against `4.4-enterprise` and it succeeded:
```
TF_ACC=1 go test $(go list ./... | grep -v 'vendor') -v  -timeout 120m
?       terraform-provider-neo4j        [no test files]
=== RUN   TestResourceDatabase                                                                                                                                                                                 
--- PASS: TestResourceDatabase (9.01s)                                                                                                                                                                         
=== RUN   TestResourceGrantV2
GRANT MATCH {*} ON GRAPH `neo4j` NODE toto TO `testRole`
GRANT MATCH {toto} ON GRAPH `neo4j` NODE toto TO `testRole`                                                                                                                                                    
GRANT SET PROPERTY {*} ON GRAPH `system` RELATIONSHIP * TO `testRole`                                                                                                                                          
GRANT SET LABEL * ON GRAPH * TO `testRole`
GRANT WRITE ON GRAPH * TO `testRole`
GRANT MERGE {*} ON GRAPH `system` RELATIONSHIP toto TO `testRole`
GRANT CREATE ON GRAPH * NODE toto TO `testRole`   
GRANT REMOVE LABEL * ON GRAPH * TO `testRole`
GRANT SET LABEL toto ON GRAPH * TO `testRole`                                                          
GRANT DELETE ON GRAPH `system` TO `testRole`
--- PASS: TestResourceGrantV2 (7.74s)
=== RUN   TestImportResourceGrantV2                                                                                                                                                                            
--- PASS: TestImportResourceGrantV2 (3.49s)                                                            
=== RUN   TestResourceRole                    
--- PASS: TestResourceRole (1.53s)
=== RUN   TestResourceUser
--- PASS: TestResourceUser (2.28s)                                                                     
PASS  
ok      terraform-provider-neo4j/neo4j  24.064s
```

**Comment by headyj** [comment]
Ok good news! I will test it on my side and release a new version

**Comment by headyj** [comment]
@egyptianbman it's done: https://registry.terraform.io/providers/headyj/neo4j/0.3.0

**Pull request merged**
