### PR TITLE
Fix: init session on system database

### PR DESCRIPTION
**Pull request by RonsenbergVI**
The `SHOW USER` query needs to be ran on the system database otherwise it raises an error.

### CODE REVIEW

**Comment by olympe-operator** [comment]
Hello, just a few question about your PR:
- On which version of Neo4j did you encounter an issue at init sessions?
- Why did you remove windows release and GPG key?

**Comment by headyj** [comment]
Hello, just a few question about your PR:

On which version of Neo4j did you encounter an issue at init sessions?
Why did you remove windows release and GPG key?

**Comment by RonsenbergVI** [comment]
> Hello, just a few question about your PR:
> 
> On which version of Neo4j did you encounter an issue at init sessions? Why did you remove windows release and GPG key?

Apologies. The only change that was meant to be in this PR were the database additions. I made the other changes to get something to work as quickly as possible from my branch (build them myself) as I need this to work asap. I'll send in a new PR with only the changes required later.

**Comment by RonsenbergVI** [comment]
I'm working on 4.4.0 - but the query seems to be working on 4.4.10

**Comment by headyj** [comment]
OK thanks @RonsenbergVI, just let me know so I can test on my side as we are using neo4j 4.1.5 and it is working without the database additions

**Pull request closed without merging**
